# Generated by Django 6.0.7 on 2026-07-12 13:20

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('normal', 'سفارش محصولات موجود'), ('custom', 'درخواست خودروی سفارشی'), ('used', 'سفارش خودروی دسته دوم')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_type', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('normal', 'سفارش محصولات موجود'), ('custom', 'درخواست خودروی سفارشی'), ('used', 'سفارش خودروی دسته دوم')], default='normal', max_length=10)),
                ('selected_color', models.CharField(blank=True, max_length=120)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('custom_car_type', models.CharField(blank=True, max_length=160)),
                ('custom_specs', models.TextField(blank=True)),
                ('custom_color', models.CharField(blank=True, max_length=120)),
                ('custom_budget_toman', models.BigIntegerField(blank=True, null=True)),
                ('deposit_terms_accepted', models.BooleanField(default=False)),
                ('deposit_terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.stage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
