# Generated by Django 6.0.7 on 2026-07-12 13:20

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_text', models.TextField(default='لطفاً پیش از واریز بیعانه، شرایط و قوانین را با دقت مطالعه کنید. مبلغ بیعانه غیرقابل بازگشت است مگر طبق شرایط قرارداد. پس از واریز، فیش را از طریق سیستم تیکتینگ ارسال نمایید.')),
                ('card_number', models.CharField(default='6037-9975-0000-0000', max_length=32)),
                ('sheba', models.CharField(default='IR000000000000000000000000', max_length=40)),
                ('card_holder', models.CharField(default='شرکت اتوگلکسی', max_length=120)),
                ('deposit_amount_toman', models.BigIntegerField(default=500000000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toman_per_aed', models.PositiveIntegerField(default=26500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
