# Generated by Django 6.0.7 on 2026-07-20 07:42

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
